version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "4022:4022"
    expose:
      - "4022"
    networks:
      - sec
    volumes:
      - ./nginx-configuration-file:/etc/nginx/conf.d/default.conf
      - ./static:/home/www-data/group22/static

  sec:
    environment:
      - BEELANCE_SECRET_KEY
      - BEELANCE_EMAIL_HOST
      - BEELANCE_EMAIL_HOST_USER
      - BEELANCE_EMAIL_HOST_PASSWORD
      - BEELANCE_EMAIL_PORT
      - BEELANCE_DEFAULT_ADMIN_PASSWORD
    build: .
    image: sec
    ports:
      - "8022:8022"
    expose:
      - "8022"
    networks:
      - sec
    volumes:
      - ./sec:/usr/src/app/sec
      - ./static:/usr/src/app/sec/static

networks:
  sec:
