FROM alpine

ARG BEELANCE_SECRET_KEY
ARG BEELANCE_EMAIL_HOST
ARG BEELANCE_EMAIL_HOST_USER
ARG BEELANCE_EMAIL_HOST_PASSWORD
ARG BEELANCE_EMAIL_PORT
ARG BEELANCE_DEFAULT_ADMIN_PASSWORD

ENV BEELANCE_SECRET_KEY ${BEELANCE_SECRET_KEY}
ENV BEELANCE_EMAIL_HOST ${BEELANCE_EMAIL_HOST}
ENV BEELANCE_EMAIL_HOST_USER ${BEELANCE_EMAIL_HOST_USER}
ENV BEELANCE_EMAIL_HOST_PASSWORD ${BEELANCE_EMAIL_HOST_PASSWORD}
ENV BEELANCE_EMAIL_PORT ${BEELANCE_EMAIL_PORT}
ENV BEELANCE_DEFAULT_ADMIN_PASSWORD ${BEELANCE_DEFAULT_ADMIN_PASSWORD}

ENV NGINX_DIR /home/www-data/group22/

RUN apk add --no-cache dos2unix

WORKDIR /tmp

COPY ./docker-entrypoint.sh ./

RUN dos2unix ./docker-entrypoint.sh

FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
COPY static $NGINX_DIR/static

RUN pip3 install --no-cache-dir -r requirements.txt

COPY --from=0 /tmp/docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh
COPY seed.json create_superuser.py ./

ENTRYPOINT ./docker-entrypoint.sh
