# Generated by Django 2.0.6 on 2019-03-18 15:34

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import projects.models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190317_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=projects.models.delivery_path, validators=[projects.validators.validate_file_extension, projects.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=projects.models.OverwriteStorage(), upload_to=projects.models.directory_path, validators=[projects.validators.validate_file_extension, projects.validators.validate_file_size]),
        ),
    ]
