# Generated by Django 2.0.6 on 2019-03-17 19:57

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190317_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=projects.models.delivery_path),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=projects.models.OverwriteStorage(), upload_to=projects.models.directory_path),
        ),
    ]
