# Generated by Django 2.0.6 on 2019-03-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190209_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'security_questions',
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestionInter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
                ('security_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SecurityQuestion')),
            ],
            options={
                'db_table': 'security_questions_inter',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='security_questions',
            field=models.ManyToManyField(through='user.SecurityQuestionInter', to='user.SecurityQuestion'),
        ),
    ]
